version: '3'
services:
  db:
    build: ./db
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - '127.0.0.1:8081:5432'

  app:
    depends_on:
      - db
    build: ./app
    ports:
      - '127.0.0.1:8080:80'
